"""is_approved true by deafult

Revision ID: c7dd747a06fd
Revises: 0c4ec9e5e354
Create Date: 2024-11-21 23:50:25.919274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7dd747a06fd'
down_revision: Union[str, None] = '0c4ec9e5e354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
